spring:
  config:
    activate:
      on-profile: test
  jpa:
    hibernate:
      ddl-auto: validate

app:
  rate-limit:
    login:
      tentativas: 3
      janela-minutos: 1

logging:
  level:
    com.barbearia: DEBUG
